<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDyr2z5n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDyr2z5n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDyr2z5n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDyr2z5n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDyr2z5n\appProdProjectContainer([
    'container.build_hash' => 'Dyr2z5n',
    'container.build_id' => 'e6717d20',
    'container.build_time' => 1705983844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDyr2z5n');
