<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzg380x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzg380x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMzg380x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMzg380x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMzg380x\appProdProjectContainer([
    'container.build_hash' => 'Mzg380x',
    'container.build_id' => 'c8ed8e79',
    'container.build_time' => 1706231399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzg380x');
